---
abstract: "dump directory structures' meta-data in a consistent and"
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Devel::CheckOS: '0'
  IO::String: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.36'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
keywords:
  - depth
  - dir
  - directory
  - dumper
  - file
  - filename
  - group
  - json
  - length
  - meta-data
  - mtime
  - permissions
  - pure-perl
  - size
  - stream
  - traverse
  - tree
  - user
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Dir-Dumper
provides:
  File::Dir::Dumper:
    file: lib/File/Dir/Dumper.pm
    version: v0.0.10
  File::Dir::Dumper::App:
    file: lib/File/Dir/Dumper/App.pm
    version: v0.0.10
  File::Dir::Dumper::Base:
    file: lib/File/Dir/Dumper/Base.pm
    version: v0.0.10
  File::Dir::Dumper::Scanner:
    file: lib/File/Dir/Dumper/Scanner.pm
    version: v0.0.10
  File::Dir::Dumper::Stream::JSON::Reader:
    file: lib/File/Dir/Dumper/Stream/JSON/Reader.pm
    version: v0.0.10
  File::Dir::Dumper::Stream::JSON::Writer:
    file: lib/File/Dir/Dumper/Stream/JSON/Writer.pm
    version: v0.0.10
requires:
  Carp: '0'
  Class::Accessor: '0'
  Devel::CheckOS: '0'
  File::Find::Object: v0.1.2
  Getopt::Long: '2.36'
  JSON::MaybeXS: '0'
  List::Util: '0'
  POSIX: '0'
  parent: '0'
  perl: '5.012'
  strict: '0'
  warnings: '0'
resources:
  homepage: http://www.shlomifish.org/open-source/projects/File-Dir-Dumper/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: http://bitbucket.org/shlomif/perl-file-dir-dumper
version: v0.0.10
